config/routes.rb
Rails.application.routes.draw do
  get '/map', to: 'maps#show'
  root 'staticpages#top'
  resources :boards, only: [:index, :new, :create, :edit, :update, :destroy]
  get 'home/top'
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  # root 'staticpages#top'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65535 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    home_top_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.includes(:user)
  end

  def new
    @board = Board.new
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def board_params
    params.require(:board).permit(:title, :body)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def show
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/boards/_form.html.erb
<%= form_with model: @board do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body, row: "10", style: "height: 200px" %>
  </div>
  <div><%= f.submit  %></div>
<% end %>

app/views/boards/edit.html.erb
<h1>投稿編集</h1>
<%= render 'form', board: @board %>

app/views/boards/index.html.erb
<!-- index.html.erb -->

<style>
  body {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
    margin: 0;
    padding: 0;
  }

  .container {
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    background-color: #fff;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    border-radius: 5px;
  }

  h1 {
    text-align: center;
    color: #333;
  }

  h2 {
    color: #007bff;
    margin-bottom: 5px;
  }

  p {
    color: #555;
  }

  span {
    display: block;
    margin-top: 5px;
    color: #888;
  }

  div.no-boards {
    text-align: center;
    color: #555;
    padding: 20px;
    background-color: #eee;
    border-radius: 5px;
    margin-top: 20px;
  }
</style>

<div class="container">
  <h1>掲示板一覧</h1>
  <% if @boards.present? %>
    <% @boards.each do |board| %>
      <div class="board">
        <h2><%= board.title %></h2>
        <p><%= board.body %></p>
        <span>
          <small><%= board.created_at %></small>
        </span>
        <%= link_to "編集" , edit_board_path(board) %>
        <%= button_to "削除" ,  board_path(board) , method: :delete %>
      </div>
    <% end %>
  <% else %>
    <div class="no-boards">掲示板がありません</div>
  <% end %>
</div>

app/views/boards/new.html.erb
<h1>新規投稿</h1>
<%= render 'form', board: @board %>

app/views/home/top.html.erb
<h1>Home#top</h1>
<%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/maps/show.html.erb
<!DOCTYPE html>
<html lang="ja">

<head>
<meta charset="UTF-8">
<title>Sample_GoogleMap</title>

<script src="http://maps.google.com/maps/api/js?key=AIzaSyDyKJ0uQI5X3lHO3by9VR7-36019CRunSU&language=ja"></script>

<style>
html { height: 100% }
body { height: 100% }
#map { height: 500px; width: 500px}
</style>
</head>

<body>
<div id="map"></div>

<script>
var MyLatLng = new google.maps.LatLng(35.6811673, 139.7670516);
var Options = {
 zoom: 15,      //地図の縮尺値
 center: MyLatLng,    //地図の中心座標
 mapTypeId: 'roadmap'   //地図の種類
};
var map = new google.maps.Map(document.getElementById('map'), Options);
</script>

</body>
</html>

app/views/shared/_header.html.erb
<header>
  <nav>
    <%= link_to 'ログイン', user_session_path %>
    <%= link_to 'トップ',root_path %>
    <%= link_to 'マップ',map_path %>
    <%= link_to '掲示板一覧',boards_path %>
    <%= link_to '新規投稿',new_board_path %>
  </nav>
</header>

app/views/staticpages/top.html.erb
<h1>top</h1>
<p>Find me in app/views/staticpages/top.html.erb</p>